{% set name = "pygeodesic" %}
{% set version = "0.1.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygeodesic-{{ version }}.tar.gz
  sha256: a9b54eb20d57f5499d8b2a4a67ece675a44c6fc8d00b11e8c14c8c99edeee5ed
  patches:
    - ptr.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ stdlib("c") }}
  host:
    - cython >=3
    - numpy
    - pip
    - python
    - setuptools >=42
    - wheel >=0.33.0
  run:
    - python

test:
  imports:
    - pygeodesic
  commands:
    - pip list
    - pip check
  requires:
    - pip
  files:
    - flat_triangular_mesh.txt

about:
  home: https://pypi.org/project/pygeodesic
  summary: Python library for calculating geodesic distance on triangular based surface meshes
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/mhogg/pygeodesic

extra:
  recipe-maintainers:
    - goanpeca
